spring.application.name=usuarios-service
server.port = 8090

# URL de conexión a Oracle. Cambia "localhost", "1521" y "XE" por tus datos
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=USUARIOS_SERVICE
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración específica de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true