# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de USUARIOS
spring.cloud.gateway.server.webflux.routes[0].id=usuarios-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://usuarios-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# Ruta para el controlador de TIPO_USUARIOS
spring.cloud.gateway.server.webflux.routes[1].id=tipos-usuarios-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://usuarios-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/tipos_usuarios/**

# Ruta para el microservicio de AUTHS
spring.cloud.gateway.server.webflux.routes[2].id=auth-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/registros/**

# Ruta para el controlador de ESTADOS
spring.cloud.gateway.server.webflux.routes[3].id=estados-auth-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/estados_registros/**

# Ruta para el microservicio de ALBUMES
spring.cloud.gateway.server.webflux.routes[4].id=albumes-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://albumes-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/albumes/**

# Ruta para el controlador de TIPO_ALBUM
spring.cloud.gateway.server.webflux.routes[5].id=tipos-albumes-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://albumes-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/tipos_albumes/**

# Ruta para el microservicio de CANCIONES
spring.cloud.gateway.server.webflux.routes[6].id=canciones-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://canciones-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/canciones/**

# Ruta para el controlador de GENERO_CANCION
spring.cloud.gateway.server.webflux.routes[7].id=generos-canciones-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://canciones-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/generos_canciones/**

# Ruta para el microservicio de REPORTES
spring.cloud.gateway.server.webflux.routes[8].id=reportes-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://reportes-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/reportes/**

# Ruta para el controlador de ESTADOS_REPORTES
spring.cloud.gateway.server.webflux.routes[9].id=estados-reportes-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://reportes-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/estados_reportes/**

# Ruta para el controlador de TIPOS_REPORTES
spring.cloud.gateway.server.webflux.routes[10].id=tipos-reportes-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://reportes-service
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/v1/tipos_reportes/**

# Ruta para el microservicio de SUSCRIPCIONES
spring.cloud.gateway.server.webflux.routes[11].id=suscripciones-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://suscripciones-service
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/v1/suscripciones/**

# Ruta para el controlador de PLANES
spring.cloud.gateway.server.webflux.routes[12].id=plan-suscripciones-service
spring.cloud.gateway.server.webflux.routes[12].uri=lb://suscripciones-service
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/v1/planes/**

# Ruta para el microservicio de REPRODUCCIONES
spring.cloud.gateway.server.webflux.routes[13].id=reproducciones-service
spring.cloud.gateway.server.webflux.routes[13].uri=lb://reproducciones-service
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/v1/reproducciones/**

# Ruta para el controlador de DISPOSITIVOS
spring.cloud.gateway.server.webflux.routes[14].id=dispositivos-reproducciones-service
spring.cloud.gateway.server.webflux.routes[14].uri=lb://reproducciones-service
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/api/v1/dispositivos_reproducciones/**

# Ruta para el microservicio de PLAYLISTS
spring.cloud.gateway.server.webflux.routes[15].id=playlists-service
spring.cloud.gateway.server.webflux.routes[15].uri=lb://playlists-service
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/api/v1/playlists/**

# Ruta para el controlador de GUARDADO-CANCIONES
spring.cloud.gateway.server.webflux.routes[16].id=playlists-service
spring.cloud.gateway.server.webflux.routes[16].uri=lb://playlists-service
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/api/v1/guardar_canciones_playlists/**

# Ruta para el controlador de PRIVACIDADES
spring.cloud.gateway.server.webflux.routes[17].id=playlists-service
spring.cloud.gateway.server.webflux.routes[17].uri=lb://playlists-service
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/api/v1/privacidades_playlists/**