CREATE DATABASE IF NOT EXISTS bd_usuarios;
CREATE DATABASE IF NOT EXISTS bd_suscripciones;
CREATE DATABASE IF NOT EXISTS bd_reproducciones;
CREATE DATABASE IF NOT EXISTS bd_reportes;
CREATE DATABASE IF NOT EXISTS bd_playlists;
CREATE DATABASE IF NOT EXISTS bd_canciones;
CREATE DATABASE IF NOT EXISTS bd_registros;
CREATE DATABASE IF NOT EXISTS bd_albumes;