
CREATE USER USUARIOS_SERVICE IDENTIFIED BY "12345" ;
CREATE USER SUSCRIPCIONES_SERVICE IDENTIFIED BY "12345";
CREATE USER REPRODUCCIONES_SERVICE IDENTIFIED BY "12345";
CREATE USER REPORTES_SERVICE IDENTIFIED BY "12345";
CREATE USER PLAYLISTS_SERVICE IDENTIFIED BY "12345";
CREATE USER CANCIONES_SERVICE IDENTIFIED BY "12345";
CREATE USER AUTH_SERVICE IDENTIFIED BY "12345";
CREATE USER ALBUMES_SERVICE IDENTIFIED BY "12345";

GRANT ALL PRIVILEGES 
TO USUARIOS_SERVICE, SUSCRIPCIONES_SERVICE, REPRODUCCIONES_SERVICE, PLAYLISTS_SERVICE, REPORTES_SERVICE, CANCIONES_SERVICE, AUTH_SERVICE, ALBUMES_SERVICE;
